# Generated by Django 2.1.7 on 2019-02-26 10:19

from django.db import migrations, models
import djongo.models.fields
import marketview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LVal18AFC', models.CharField(max_length=50)),
                ('InsCode', models.CharField(max_length=20)),
                ('InstrumentID', models.CharField(max_length=12)),
                ('CIsin', models.CharField(max_length=12)),
                ('Title', models.CharField(max_length=255)),
                ('DailyDatas', djongo.models.fields.ArrayModelField(model_container=marketview.models.DailyData)),
            ],
        ),
    ]
